title: PogO
author: Someone dumb
email: ienjoycolddogs@colddogswholefood.org
description: > # this means to ignore newlines until "baseurl:"
  hi everyone today i will show you how to get girls and look swag and impress ur parents
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
